# Generated by Django 4.2.11 on 2024-03-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanx_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricealert',
            name='email',
        ),
        migrations.AddField(
            model_name='pricealert',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
