# Generated by Django 4.2.11 on 2024-03-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanx_project', '0002_remove_pricealert_email_pricealert_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrencyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
